#!/bin/sh -eu

FONT_NAME=source-code-pro-1.017R

git clone https://github.com/Lokaltog/vim-powerline.git

wget "https://github.com/adobe-fonts/source-code-pro/archive/1.017R.zip"
unzip 1.017R.zip

mkdir pached

fontforge -lang=py -script ./vim-powerline/fontpatcher/fontpatcher "./${FONT_NAME}/OTF/SourceCodePro-Black.otf"
fontforge -lang=py -script ./vim-powerline/fontpatcher/fontpatcher "./${FONT_NAME}/OTF/SourceCodePro-Bold.otf"
fontforge -lang=py -script ./vim-powerline/fontpatcher/fontpatcher "./${FONT_NAME}/OTF/SourceCodePro-ExtraLight.otf"
fontforge -lang=py -script ./vim-powerline/fontpatcher/fontpatcher "./${FONT_NAME}/OTF/SourceCodePro-Light.otf"
fontforge -lang=py -script ./vim-powerline/fontpatcher/fontpatcher "./${FONT_NAME}/OTF/SourceCodePro-Medium.otf"
fontforge -lang=py -script ./vim-powerline/fontpatcher/fontpatcher "./${FONT_NAME}/OTF/SourceCodePro-Regular.otf"
fontforge -lang=py -script ./vim-powerline/fontpatcher/fontpatcher "./${FONT_NAME}/OTF/SourceCodePro-Semibold.otf"

mv *.otf pached/.

rm -rf 1.017R.zip ${FONT_NAME} vim-powerline 
